= Rotaract Unfiltered MU
Rotaract Germany

ifdef::env-github[]
:tip-caption: 💡
:note-caption: ℹ
:important-caption: ❗
:caution-caption: 🔥
:warning-caption: ⚠
endif::[]

:badge_url: https://img.shields.io
:custom_badge: {badge_url}/badge
:repo_path: rotaract/rotaract-unfiltered-mu

:year: 2021

// General Badges
image:{custom_badge}/Open_Source-❤-orange[Open Source, link="https://opensource.org"] +
image:{custom_badge}/code_style-WordPress-brightgreen[Code Style, link="https://make.wordpress.org/core/handbook/best-practices/coding-standards/"]
//   * Coding Style
//   * Rotaract Badge
//   * Framework
//   * Keywords
// Status Badges
//   * Build Status
//   * Maintenance
image:https://img.shields.io/maintenance/yes/{year}[Maintenance Status]

== Overview

https://wordpress.org/[WordPress] plugin that adds the `unfiltered_html` capability to Administrators and Editors so that content posted by users with those roles is not filtered by KSES; Embeds, Iframe, etc. are preserved.
Note: If for any reason the `unfiltered_html` capability is ever lost, simply deactivate, and then reactivate this plugin.

== 🔧 Setup / Installation

.Prerequisites
[NOTE]
--
* ...
--

=== Usage

== Code of Conduct

Please note that this project is release with the link:CODE_OF_CONDUCT.adoc[Contributor Covenant Code of Conduct].
By contributing to this project, you agree to abide by its terms.

== ⚖️ Legal Notices

Copyright © 2021, Rotaract Deutschland

Licensed under European Union Public License 1.2 (EUPL-1.2).

_Rotary_, _Rotaract_, and _Interact_ are trademarks or registered trademarks of Rotary International and are used with the permission of Rotary International.
Other trademarks not owned by Rotary International are the property of their respective owners.
The license above does not grant any rights under trademark law and all such rights are reserved.
Modified versions must be renamed to avoid use of any Rotary International trademarks, including but not limited to _Rotary_, _Rotaract_, and _Interact_.

All Rotary, Rotaract, and Interact logos and graphics are under copyright.
