name: Build WordPress Plugin ZIP

on:
  push:
    branch: [ master ]
  pull_request:
    branch: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: rotaract-unfiltered-mu
          path: |
            ./*
            !tmp
            !.*
